### ISSUE TITLE
Question regarding using Vivid with Exa

### ISSUE THREAD

**Issue by eo1989** [sharkdp/vivid#41]
Hello, 

I'm curious if there is a way to get the vivid color database (in my case, snazzy) ported through exa so when anyone types "Exa" in a directory Exa's default color scheme runs Vivid's instead. Exa is a more advanced "ls" implementation for those not in the know, and it comes with it's own color scheme/template. You can hardcode an LS_COLORS and/or EXA_COLORS env variables, but idk how to port vivids .yaml color codes into env variable expressions. I suppose vivid works well with Bat & Fd. Curious if it works with exa also..

MacOS X v. 10.15.6
Vivid v.0.5.0
Exa v.0.9.0
Bat v.0.15.4
Fd v.8.1.1
Homebrew 2.4.13-105-gd3e22f4

**Comment by sharkdp** [comment]
Thank you for your feedback.

> I suppose vivid works well with Bat & Fd. Curious if it works with exa also..

`vivid` works with `fd` because `vivid` generates an `LS_COLORS` expression and `fd` reads that from the environment, just like `ls` or `tree`.

I don't see how `vivid` is related to `bat`? `bat` themes are something else entirely.

> Curious if it works with exa also..

It could work with `exa` if `exa` reads `LS_COLORS` as well. I don't know `exa`s `EXA_COLORS` format, so I can't really tell if it would be possible to support it. I might be convinced to add special support for `exa` if that turns out to align with `vivid`s goals. But I'm most probably not going to work on this myself.

**Comment by LordFlashmeow** [comment]
@eo1989, If you set `LS_COLORS` with vivid in `.bashrc` using `export LS_COLORS="$(vivid generate molokai)"`, `exa` should pick up on that and use the colors generated by vivid instead.

**Comment by sharkdp** [comment]
@eo1989 Any feedback on this?
